import type { StoredSubmission } from '@/lib/admin/submissions'
import type { BlogPost } from '@/lib/blog/types'

/**
 * Realistic fake data for demo mode — enough variety across tracks,
 * verticals, cities, and genders that the dashboard's charts and the
 * submissions filter actually look populated, not empty or repetitive.
 */

const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString()

export const DEMO_SUBMISSIONS: StoredSubmission[] = [
  {
    id: 'demo-founder-1',
    track: 'founder',
    submittedAt: daysAgo(2),
    values: {
      startupName: 'Chaman Crafts',
      primaryFounderName: 'Ayesha Raza',
      vertical: 'handicrafts',
      stage: 'mvp',
      cityProvince: 'Lahore, Punjab',
      gender: 'female',
    },
    analytics: { vertical: 'handicrafts', stage: 'mvp', availability: true, funded: false, city: 'Lahore', gender: 'female', source: 'social-media' },
    meta: { userAgent: 'demo', locale: 'en' },
  },
  {
    id: 'demo-founder-2',
    track: 'founder',
    submittedAt: daysAgo(5),
    values: {
      startupName: 'Sehat Sakhi',
      primaryFounderName: 'Mahnoor Khalid',
      vertical: 'health-wellness',
      stage: 'prototype',
      cityProvince: 'Karachi, Sindh',
      gender: 'female',
    },
    analytics: { vertical: 'health-wellness', stage: 'prototype', availability: true, funded: false, city: 'Karachi', gender: 'female', source: 'peer-referral' },
    meta: { userAgent: 'demo', locale: 'en' },
  },
  {
    id: 'demo-founder-3',
    track: 'founder',
    submittedAt: daysAgo(9),
    values: {
      startupName: 'Taleem Tech',
      primaryFounderName: 'Sana Iftikhar',
      vertical: 'education-training',
      stage: 'idea',
      cityProvince: 'Islamabad',
      gender: 'female',
    },
    analytics: { vertical: 'education-training', stage: 'idea', availability: true, funded: false, city: 'Islamabad', gender: 'female', source: 'email' },
    meta: { userAgent: 'demo', locale: 'en' },
  },
  {
    id: 'demo-founder-4',
    track: 'founder',
    submittedAt: daysAgo(13),
    values: {
      startupName: 'Zaiqa Foods',
      primaryFounderName: 'Rabia Aslam',
      vertical: 'food-beverages',
      stage: 'established',
      cityProvince: 'Faisalabad, Punjab',
      gender: 'female',
    },
    analytics: { vertical: 'food-beverages', stage: 'established', availability: false, funded: true, city: 'Faisalabad', gender: 'female', source: 'social-media' },
    meta: { userAgent: 'demo', locale: 'en' },
  },
  {
    id: 'demo-founder-5',
    track: 'founder',
    submittedAt: daysAgo(18),
    values: {
      startupName: 'Rangreza Studio',
      primaryFounderName: 'Hira Yousaf',
      vertical: 'creative-industries',
      stage: 'mvp',
      cityProvince: 'Multan, Punjab',
      gender: 'female',
    },
    analytics: { vertical: 'creative-industries', stage: 'mvp', availability: true, funded: false, city: 'Multan', gender: 'female', source: 'peer-referral' },
    meta: { userAgent: 'demo', locale: 'en' },
  },
  {
    id: 'demo-founder-6',
    track: 'founder',
    submittedAt: daysAgo(22),
    values: {
      startupName: 'Souk Al-Elm',
      primaryFounderName: 'Fatima Noor',
      vertical: 'ecommerce',
      stage: 'prototype',
      cityProvince: 'Peshawar, KP',
      gender: 'female',
    },
    analytics: { vertical: 'ecommerce', stage: 'prototype', availability: true, funded: false, city: 'Peshawar', gender: 'female', source: 'print-electronic-media' },
    meta: { userAgent: 'demo', locale: 'en' },
  },
  {
    id: 'demo-enterprise-1',
    track: 'enterprise',
    submittedAt: daysAgo(3),
    values: {
      businessName: 'Nazuk Beauty Bar',
      primaryContactName: 'Iqra Shahid',
      vertical: 'beauty-wellness',
      cityProvince: 'Lahore, Punjab',
      gender: 'female',
    },
    analytics: { vertical: 'beauty-wellness', city: 'Lahore', gender: 'female', source: 'social-media' },
    meta: { userAgent: 'demo', locale: 'en' },
  },
  {
    id: 'demo-enterprise-2',
    track: 'enterprise',
    submittedAt: daysAgo(8),
    values: {
      businessName: 'Bunyan Stitches',
      primaryContactName: 'Sadia Malik',
      vertical: 'fashion-apparel',
      cityProvince: 'Rawalpindi, Punjab',
      gender: 'female',
    },
    analytics: { vertical: 'fashion-apparel', city: 'Rawalpindi', gender: 'female', source: 'peer-referral' },
    meta: { userAgent: 'demo', locale: 'en' },
  },
  {
    id: 'demo-enterprise-3',
    track: 'enterprise',
    submittedAt: daysAgo(15),
    values: {
      businessName: 'Ghar Ka Dastarkhwan',
      primaryContactName: 'Nimra Baig',
      vertical: 'food-beverages',
      cityProvince: 'Quetta, Balochistan',
      gender: 'female',
    },
    analytics: { vertical: 'food-beverages', city: 'Quetta', gender: 'female', source: 'social-media' },
    meta: { userAgent: 'demo', locale: 'en' },
  },
  {
    id: 'demo-mentor-1',
    track: 'mentor',
    submittedAt: daysAgo(4),
    values: {
      fullName: 'Bilal Ahmed',
      currentRole: 'VP Product, fintech scale-up',
      cityProvince: 'Karachi, Sindh',
      expertiseAreas: 'Product strategy, fundraising',
    },
    analytics: { expertise: 'product-strategy', city: 'Karachi' },
    meta: { userAgent: 'demo', locale: 'en' },
  },
  {
    id: 'demo-mentor-2',
    track: 'mentor',
    submittedAt: daysAgo(11),
    values: {
      fullName: 'Dr. Saima Farooq',
      currentRole: 'Founder, HealthTech accelerator',
      cityProvince: 'Islamabad',
      expertiseAreas: 'HealthTech, regulatory',
    },
    analytics: { expertise: 'healthtech', city: 'Islamabad' },
    meta: { userAgent: 'demo', locale: 'en' },
  },
  {
    id: 'demo-partner-1',
    track: 'partner',
    submittedAt: daysAgo(6),
    values: {
      organizationName: 'Meezan Ventures',
      contactName: 'Usman Tariq',
      cityProvince: 'Lahore, Punjab',
      partnerCategory: 'investor',
    },
    analytics: { partnerCategory: 'investor', city: 'Lahore' },
    meta: { userAgent: 'demo', locale: 'en' },
  },
  {
    id: 'demo-partner-2',
    track: 'partner',
    submittedAt: daysAgo(17),
    values: {
      organizationName: 'LUMS Center for Entrepreneurship',
      contactName: 'Dr. Ali Raza',
      cityProvince: 'Lahore, Punjab',
      partnerCategory: 'academic',
    },
    analytics: { partnerCategory: 'academic', city: 'Lahore' },
    meta: { userAgent: 'demo', locale: 'en' },
  },
]

export const DEMO_BLOG_POSTS: BlogPost[] = [
  {
    id: 'demo-post-1',
    slug: 'welcome-to-wise-lab',
    title: 'Welcome to WISE Lab: From Cocoon to Flight',
    excerpt: 'An introduction to Pakistan’s flagship platform for women-led innovation and enterprise.',
    content:
      '# Welcome to WISE Lab\n\nWISE Lab exists because her idea was never small — the room was. This is where that changes.',
    coverImageUrl: null,
    author: 'WISE Lab Team',
    publishedAt: daysAgo(20),
    status: 'published',
    tags: ['announcement'],
    section: 'wise-journey',
  },
  {
    id: 'demo-post-2',
    slug: 'first-cohort-applications-open',
    title: 'Applications Now Open for the First Founder Flightpath Cohort',
    excerpt: 'Women founders across Pakistan can now apply for structured incubation support.',
    content: '# Applications are open\n\nWe are accepting applications for the first Founder Flightpath cohort.',
    coverImageUrl: null,
    author: 'WISE Lab Team',
    publishedAt: daysAgo(10),
    status: 'published',
    tags: ['cohort', 'applications'],
    section: 'build-tracks',
  },
  {
    id: 'demo-post-3',
    slug: 'draft-mentor-spotlight',
    title: '(Draft) Mentor Spotlight Series',
    excerpt: 'Upcoming series profiling WISE Lab mentors — not yet published.',
    content: '# Mentor Spotlight\n\nDraft content, still being written.',
    coverImageUrl: null,
    author: 'WISE Lab Team',
    publishedAt: null,
    status: 'draft',
    tags: ['mentors'],
    section: 'become-a-mentor',
  },
]
